# Statistics - Task 1

## 1. The historical average score in a certification exam is 65. A training institute introduces a new course. A random sample of 50 students trained under the new course has an average score of 68. At the 5% level of significance, test whether the new course improves performance.

In [2]:
# H0 : Current process / Statement of No change - There is no significant difference in average score
# H1 : Statement of Change - The average score has increased 

In [3]:
from scipy import stats
import numpy as np

In [4]:
# Generating random array of numbers with mean as 68

In [13]:
observations1 = np.random.normal(loc=68, scale=5, size=50).astype("int")

In [14]:
observations1

array([59, 68, 73, 64, 76, 63, 57, 62, 68, 68, 69, 65, 72, 58, 67, 71, 63,
       74, 67, 82, 63, 66, 66, 69, 66, 68, 70, 66, 74, 70, 65, 73, 58, 72,
       73, 64, 59, 69, 72, 64, 67, 71, 70, 72, 77, 77, 69, 73, 68, 63])

In [10]:
# ttest 1 sample with one sided 

In [15]:
stats.ttest_1samp(a = observations1,popmean = 65, alternative = "greater")

TtestResult(statistic=np.float64(3.9743086115484387), pvalue=np.float64(0.00011581447198865632), df=np.int64(49))

In [31]:
# From the tuple, taking only pvalue separately

In [29]:
tstats,pvalue1 = stats.ttest_1samp(a = observations1,popmean = 65, alternative = "greater")

In [30]:
pvalue1 

np.float64(0.00011581447198865632)

In [32]:
# Coming to conclusion

In [35]:
if pvalue1 < 0.05 :
    print("We reject H0")
else:
    print("We do not reject H0")

We reject H0


In [36]:
# At 5% level of significance, we can reject the Null Hypothesis and claim that the average score has indeed increased

## 2. A company claims that the average time taken to resolve customer tickets is 30 minutes. A random sample of 40 tickets shows a mean resolution time of 33 minutes. At the 5% level of significance, test whether the average resolution time has increased.

In [2]:
# H0 : Current process / Statement of No change - There is no significant difference in average resolution time. 
# H1 : Statement of Change - The average resolution time has increased. 

In [4]:
from scipy import stats
import numpy as np

In [ ]:
# Generating array of random numbers with mean as 33 

In [16]:
observations2 = np.random.normal(loc=33, scale=5, size=40).astype("int")

In [17]:
observations2

array([32, 35, 31, 36, 39, 26, 30, 34, 36, 29, 34, 36, 32, 28, 31, 30, 22,
       25, 29, 34, 31, 35, 26, 33, 34, 36, 26, 34, 31, 33, 33, 28, 30, 36,
       35, 26, 27, 30, 24, 41])

In [ ]:
# ttest 1 sample with one sided 

In [18]:
 stats.ttest_1samp(a = observations2,popmean = 30,alternative = "greater")

TtestResult(statistic=np.float64(2.164772711292327), pvalue=np.float64(0.018293227158502137), df=np.int64(39))

In [ ]:
# From the tuple, taking only pvalue separately

In [25]:
t_stats,pvalue2 = stats.ttest_1samp(a = observations2,popmean = 30,alternative = "greater")

In [26]:
t_stats,pvalue2

(np.float64(2.164772711292327), np.float64(0.018293227158502137))

In [27]:
pvalue2

np.float64(0.018293227158502137)

In [ ]:
# Coming to conclusion

In [28]:
if pvalue2 < 0.05 : 
    print("We Reject H0")
else:
    print("We do not reject H0")

We Reject H0


In [24]:
# At 5% level of significance, we can reject the Null Hypothesis and claim that the average resolution time has indeed increased

## 3. A company claims that 60% of its users are satisfied with its product. In a survey of 200 users, 134 users report satisfaction. At the 5% level of significance, test whether customer satisfaction is higher than claimed.

In [7]:
# H0 : Current process / Statement of No change - There is no significant difference in customer satisfaction
# H1 : Statement of Change - The customer satisfaction has increased

In [2]:
from scipy import stats
import numpy as np

In [1]:
# Since the mean is not given and its in percentage, we go with z-test

In [3]:
# Given
p0 = 0.60
n = 200
x = 134

# Convert to "observations" (1 = satisfied, 0 = not satisfied)
observations3 = np.array([1]*134 + [0]*(200-134))

observations3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [4]:
# Sample proportion
p_hat = np.mean(observations3)

# Standard error
se = np.sqrt(p0 * (1 - p0) / n)

# Z-statistic
z_stat = (p_hat - p0) / se

# One-sided p-value
pvalue3 = 1 - stats.norm.cdf(z_stat)

z_stat, pvalue3

(np.float64(2.020725942163692), np.float64(0.02165407140539588))

In [5]:
if pvalue3 < 0.05:
    print("We Reject H0")
else:
    print("We do not reject H0")

We Reject H0


In [6]:
# At 5% level of significance, we can reject the Null Hypothesis and claim that the customer satisfaction has increased

## 4. Historically, 40% of applicants pass an entrance test. After a new preparation program, 90 out of 180 applicants pass. Test at the 5% level of significance whether the pass rate has improved.

In [8]:
# H0 : Current process / Statement of No change - There is no significant difference in pass percentage
# H1 : Statement of Change - The average pass percentage has increased

In [2]:
from scipy import stats
import numpy as np

In [10]:
# Since the mean is in percentage, we use z-test

In [6]:
# Given
p0 = 0.40
n = 180
x = 90

# Convert to "observations" (1 = satisfied, 0 = not satisfied)
observations4 = np.array([1]*90 + [0]*(180-90))

observations4

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [7]:
# Sample proportion
p_hat = np.mean(observations4)

# Standard error
se = np.sqrt(p0 * (1 - p0) / n)

# Z-statistic
z_stat = (p_hat - p0) / se

# One-sided p-value
pvalue4 = 1 - stats.norm.cdf(z_stat)

z_stat, pvalue4

(np.float64(2.73861278752583), np.float64(0.0030849496602720627))

In [8]:
if pvalue4 < 0.05:
    print("We Reject H0")
else:
    print("We do not reject H0")

We Reject H0


In [9]:
# At 5% level of significance, we can reject the Null Hypothesis and claim that the pass rate has increased.

## 5. Two teaching methods are used to train employees. A sample of 30 employees trained using Method A and 28 employees trained using Method B are tested. Test at the 5% level of significance whether there is a difference in average scores between the two methods.

In [ ]:
# Two tailed test

In [10]:
# H0 : Null Hypothesis : Statement of no change, there is no significant change betweem the two methods

In [11]:
# H1 : Alternate Hypothesis : Statement of change, there is a difference in averagew scores between two methods.

In [3]:
from scipy import stats
import numpy as np

In [4]:
np.random.seed(0)

In [5]:
# Sample data 

In [6]:
method_A = np.random.normal(loc=70, scale=8, size=30)
method_B = np.random.normal(loc=75, scale=8, size=28)

In [7]:
method_A, method_B

(array([84.11241877, 73.20125767, 77.82990387, 87.92714559, 84.94046392,
        62.18177696, 77.60070734, 68.78914233, 69.17424919, 73.28478802,
        71.15234857, 81.63418806, 76.0883018 , 70.97340013, 73.55090586,
        72.66939462, 81.95263259, 68.35873389, 72.50454161, 63.16723409,
        49.57608147, 75.22894876, 76.91548959, 64.06267984, 88.15803699,
        58.3650746 , 70.36606814, 68.5025292 , 82.26223371, 81.75487016]),
 array([76.23957941, 78.02530016, 67.89771402, 59.15362825, 72.21670281,
        76.25079175, 84.84232545, 84.61903879, 71.90138546, 72.581578  ,
        66.61157628, 63.6398565 , 61.34983847, 90.60620316, 70.92278255,
        71.49540559, 64.97763712, 81.21992285, 62.08881722, 73.29807776,
        67.83626751, 78.09521998, 70.9135589 , 65.55494253, 74.77454217,
        78.42665496, 75.53213778, 77.41977518]))

In [8]:
# Performing test

In [9]:
t_test, pvalue = stats.ttest_ind(method_A, method_B)

t_test,pvalue

(np.float64(0.3421285481485949), np.float64(0.7335348699806125))

In [10]:
if pvalue < 0.05:
    print("We Reject H0")
else:
    print("We do not reject H0")

We do not reject H0


In [11]:
# At 5% level of significance, we do not reject the Null hypothesis and claim that there is no significant difference in average scores.

## 6. The average delivery time from Warehouse A and Warehouse B is compared using random samples from both warehouses. At the 5% level of significance, test whether the mean delivery times differ.

In [1]:
# H0 : Null Hypothesis : Statement of no change, there is no significant change betweem delivery time

In [2]:
# H1 : Alternate Hypothesis : Statement of change, there is a difference in delivery time from both warehouses.

In [10]:
from scipy import stats
import numpy as np

In [ ]:
# Random delivery time in minutes 

In [11]:
method_A = np.random.normal(loc=50, scale=6, size=30)
method_B = np.random.normal(loc=55, scale=6, size=32)

In [13]:
method_A , method_B

(array([50.29196181, 61.14762403, 56.31079917, 48.95791237, 41.97291296,
        38.64545037, 40.09063387, 45.98080113, 49.51027287, 44.4955654 ,
        41.11075668, 46.44058524, 48.26294999, 54.76726032, 50.0738567 ,
        38.32131659, 54.2077844 , 59.69466603, 48.48304849, 47.85119026,
        36.93737856, 54.84179361, 49.91227631, 54.60163107, 52.40802007,
        54.47963199, 45.84971902, 46.69988902, 44.78057414, 37.03567834]),
 array([53.75035951, 58.58128531, 55.55719006, 48.08830594, 57.69026657,
        46.93300348, 54.84251391, 55.49607387, 57.49451382, 48.25556907,
        56.47331179, 58.3616622 , 63.09004542, 57.99850418, 69.18474403,
        56.70471184, 50.71700167, 45.43467578, 56.0773786 , 57.96428921,
        62.80322364, 53.92031748, 55.77920023, 54.62793646, 52.28948646,
        50.69890506, 61.88227007, 55.09309857, 57.46202981, 59.7042379 ,
        55.84036379, 52.24409483]))