# Statistics - Task 1

## 1. The historical average score in a certification exam is 65. A training institute introduces a new course. A random sample of 50 students trained under the new course has an average score of 68. At the 5% level of significance, test whether the new course improves performance.

In [ ]:
# H0 : Current process / Statement of No change - There is no significant difference in average score
# H1 : Statement of Change - The average score has increased 

In [ ]:
from scipy import stats
import numpy as np

In [ ]:
# Generating random array of numbers with mean as 68

In [ ]:
observations1 = np.random.normal(loc=68, scale=5, size=50).astype("int")

In [ ]:
observations1

In [ ]:
# ttest 1 sample with one sided 

In [ ]:
stats.ttest_1samp(a = observations1,popmean = 65, alternative = "greater")

In [ ]:
# From the tuple, taking only pvalue separately

In [ ]:
tstats,pvalue1 = stats.ttest_1samp(a = observations1,popmean = 65, alternative = "greater")

In [ ]:
pvalue1 

In [ ]:
# Coming to conclusion

In [ ]:
if pvalue1 < 0.05 :
    print("We reject H0")
else:
    print("We do not reject H0")

In [ ]:
# At 5% level of significance, we can reject the Null Hypothesis and claim that the average score has indeed increased

## 2. A company claims that the average time taken to resolve customer tickets is 30 minutes. A random sample of 40 tickets shows a mean resolution time of 33 minutes. At the 5% level of significance, test whether the average resolution time has increased.

In [ ]:
# H0 : Current process / Statement of No change - There is no significant difference in average resolution time. 
# H1 : Statement of Change - The average resolution time has increased. 

In [ ]:
from scipy import stats
import numpy as np

In [ ]:
# Generating array of random numbers with mean as 33 

In [ ]:
observations2 = np.random.normal(loc=33, scale=5, size=40).astype("int")

In [ ]:
observations2

In [ ]:
# ttest 1 sample with one sided 

In [ ]:
 stats.ttest_1samp(a = observations2,popmean = 30,alternative = "greater")

In [ ]:
# From the tuple, taking only pvalue separately

In [ ]:
t_stats,pvalue2 = stats.ttest_1samp(a = observations2,popmean = 30,alternative = "greater")

In [ ]:
t_stats,pvalue2

In [ ]:
pvalue2

In [ ]:
# Coming to conclusion

In [ ]:
if pvalue2 < 0.05 : 
    print("We Reject H0")
else:
    print("We do not reject H0")

In [ ]:
# At 5% level of significance, we can reject the Null Hypothesis and claim that the average resolution time has indeed increased

## 3. A company claims that 60% of its users are satisfied with its product. In a survey of 200 users, 134 users report satisfaction. At the 5% level of significance, test whether customer satisfaction is higher than claimed.

In [ ]:
# H0 : Current process / Statement of No change - There is no significant difference in customer satisfaction
# H1 : Statement of Change - The customer satisfaction has increased

In [ ]:
from scipy import stats
import numpy as np

In [ ]:
# Since the mean is not given and its in percentage, we go with z-test

In [ ]:
# Given
p0 = 0.60
n = 200
x = 134

# Convert to "observations" (1 = satisfied, 0 = not satisfied)
observations3 = np.array([1]*134 + [0]*(200-134))

observations3

In [ ]:
# Sample proportion
p_hat = np.mean(observations3)

# Standard error
se = np.sqrt(p0 * (1 - p0) / n)

# Z-statistic
z_stat = (p_hat - p0) / se

# One-sided p-value
pvalue3 = 1 - stats.norm.cdf(z_stat)

z_stat, pvalue3

In [ ]:
if pvalue3 < 0.05:
    print("We Reject H0")
else:
    print("We do not reject H0")

In [ ]:
# At 5% level of significance, we can reject the Null Hypothesis and claim that the customer satisfaction has increased

## 4. Historically, 40% of applicants pass an entrance test. After a new preparation program, 90 out of 180 applicants pass. Test at the 5% level of significance whether the pass rate has improved.

In [ ]:
# H0 : Current process / Statement of No change - There is no significant difference in pass percentage
# H1 : Statement of Change - The average pass percentage has increased

In [ ]:
from scipy import stats
import numpy as np

In [ ]:
# Since the mean is in percentage, we use z-test

In [ ]:
# Given
p0 = 0.40
n = 180
x = 90

# Convert to "observations" (1 = satisfied, 0 = not satisfied)
observations4 = np.array([1]*90 + [0]*(180-90))

observations4

In [ ]:
# Sample proportion
p_hat = np.mean(observations4)

# Standard error
se = np.sqrt(p0 * (1 - p0) / n)

# Z-statistic
z_stat = (p_hat - p0) / se

# One-sided p-value
pvalue4 = 1 - stats.norm.cdf(z_stat)

z_stat, pvalue4

In [ ]:
if pvalue4 < 0.05:
    print("We Reject H0")
else:
    print("We do not reject H0")

In [ ]:
# At 5% level of significance, we can reject the Null Hypothesis and claim that the pass rate has increased.

## 5. Two teaching methods are used to train employees. A sample of 30 employees trained using Method A and 28 employees trained using Method B are tested. Test at the 5% level of significance whether there is a difference in average scores between the two methods.

In [ ]:
# Two tailed test

In [ ]:
# H0 : Null Hypothesis : Statement of no change, there is no significant change betweem the two methods

In [ ]:
# H1 : Alternate Hypothesis : Statement of change, there is a difference in averagew scores between two methods.

In [ ]:
from scipy import stats
import numpy as np

In [ ]:
np.random.seed(0)

In [ ]:
# Sample data 

In [ ]:
method_A = np.random.normal(loc=70, scale=8, size=30)
method_B = np.random.normal(loc=75, scale=8, size=28)

In [ ]:
method_A, method_B

In [ ]:
# Performing test

In [ ]:
t_test, pvalue = stats.ttest_ind(method_A, method_B)

t_test,pvalue

In [ ]:
if pvalue < 0.05:
    print("We Reject H0")
else:
    print("We do not reject H0")

In [ ]:
# At 5% level of significance, we do not reject the Null hypothesis and claim that there is no significant difference in average scores.

## 6. The average delivery time from Warehouse A and Warehouse B is compared using random samples from both warehouses. At the 5% level of significance, test whether the mean delivery times differ.

In [ ]:
# H0 : Null Hypothesis : Statement of no change, there is no significant change betweem delivery time

In [ ]:
# H1 : Alternate Hypothesis : Statement of change, there is a difference in delivery time from both warehouses.

In [ ]:
from scipy import stats
import numpy as np

In [ ]:
# Random delivery time in minutes 

In [ ]:
method_A = np.random.normal(loc=50, scale=6, size=30)
method_B = np.random.normal(loc=55, scale=6, size=32)

In [ ]:
method_A , method_B

In [ ]:
# Performing test

In [ ]:
ttest, pvalue = stats.ttest_ind(a=method_A,b=method_B)

In [ ]:
ttest, pvalue

In [ ]:
pvalue 

In [ ]:
if pvalue < 0.05:
    print("We Reject H0")
else:
    print("We do not reject H0")

In [ ]:
# At 5% level of significance, we can reject the Null Hypothesis and claim that the mean delivery time has increased.

## 7. Two versions of a website are tested. Out of 500 users for Version A, 320 users click the signup button. Out of 480 users for Version B, 290 users click the signup button. At the 5% level of significance, test whether the conversion rates differ.

In [ ]:
# H0 : Null Hypothesis : Statement of no change, there is no significant change in conversion rates.

In [ ]:
# H1 : Alternate Hypothesis : Statement of change, there is a difference in conversion rates.

In [ ]:
from scipy import stats
import numpy as np

In [ ]:
# Given

In [ ]:
x1, n1 = 320, 500
x2, n2 = 290, 480

In [ ]:
# Sample proportions

In [ ]:
p1 = x1 / n1
p2 = x2 / n2

In [ ]:
# Pooled proportion
p = (x1 + x2) / (n1 + n2)

# Standard error
se = np.sqrt(p * (1 - p) * (1/n1 + 1/n2))

# Z statistic
z_stat = (p1 - p2) / se

# Two-tailed p-value
pvalue = 2 * (1 - stats.norm.cdf(abs(z_stat)))

z_stat, pvalue

In [ ]:
if pvalue < 0.05:
    print("We Reject H0")
else:
    print("We do not reject H0")

In [ ]:
# At 5% level of significance, we do not reject the Null hypothesis and claim that there is no significant change in conversion rates.

## 8. A vaccine is tested in two regions. In Region A, 180 out of 300 people recover. In Region B, 165 out of 310 people recover. Test whether the recovery rates are significantly different.

In [37]:
# H0 : Null Hypothesis : Statement of no change, there is no significant change in recovery rates.

In [38]:
# H1 : Alternate Hypothesis : Statement of change, there is a difference in recovery rates.

In [40]:
from scipy import stats
import numpy as np

In [41]:
# Given
x1, n1 = 180, 300
x2, n2 = 165, 310

In [42]:
# Sample proportions
p1 = x1 / n1
p2 = x2 / n2

# Pooled proportion
p = (x1 + x2) / (n1 + n2)

# Standard error
se = np.sqrt(p * (1 - p) * (1/n1 + 1/n2))

# Z statistic
z_stat = (p1 - p2) / se

# Two-tailed p-value
pvalue = 2 * (1 - stats.norm.cdf(abs(z_stat)))

z_stat, pvalue

(np.float64(1.6874523112864297), np.float64(0.09151641239095087))

In [43]:
if pvalue < 0.05:
    print("We Reject H0")
else:
    print("We do not reject H0")

We do not reject H0


In [44]:
# At 5% level of significance, we do not reject the Null hypothesis and claim that there is no significant change in vaccine recovery.

## 9. A company wants to compare the average productivity of employees trained using three different training programs. At the 5% level of significance, test whether there is a difference in mean productivity across the programs.

In [45]:
# H0 : Current process / Statement of No change - There is no significant difference in mean productivity
# H1 : Statement of Change - There is significant difference in mean productivity across the programs 

In [46]:
# ANOVA Test 

In [47]:
import numpy as np
from scipy import stats

np.random.seed(0)

# Simulated productivity scores
program_A = np.random.normal(loc=70, scale=5, size=30)
program_B = np.random.normal(loc=75, scale=5, size=30)
program_C = np.random.normal(loc=72, scale=5, size=30)

program_A, program_B, program_C

(array([78.82026173, 72.00078604, 74.89368992, 81.204466  , 79.33778995,
        65.1136106 , 74.75044209, 69.24321396, 69.48390574, 72.05299251,
        70.72021786, 77.27136753, 73.80518863, 70.60837508, 72.21931616,
        71.66837164, 77.47039537, 68.97420868, 71.56533851, 65.7295213 ,
        57.23505092, 73.26809298, 74.32218099, 66.2891749 , 81.34877312,
        62.72817163, 70.22879259, 69.06408075, 77.66389607, 77.34679385]),
 array([75.77473713, 76.8908126 , 70.56107126, 65.09601766, 73.26043925,
        75.78174485, 81.1514534 , 81.01189924, 73.06336591, 73.48848625,
        69.75723517, 67.89991031, 66.46864905, 84.75387698, 72.45173909,
        72.80962849, 68.7360232 , 78.88745178, 66.93051076, 73.9362986 ,
        70.52266719, 76.93451249, 72.44597431, 69.09683908, 74.85908886,
        77.14165935, 75.33258611, 76.51235949, 71.82838953, 73.18629417]),
 array([68.63769776, 70.20223419, 67.93426859, 63.36858699, 72.88713071,
        69.99109532, 63.84900827, 74.31391128, 

In [50]:
f_stat,pvalue = stats.f_oneway(program_A, program_B, program_C)

In [51]:
f_stat,pvalue

(np.float64(1.5117235305152548), np.float64(0.2262649167715853))